# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a41e471c346c9adcfad267c8fe4f42010eeeef1bf766684483996bb5c12e59d20940d6264d35d7ac96b127373eedbe700e2fa26a8c2719c444f34ea74c7b055f

test:
  secret_key_base: 0c0ba4274932027a265f0da12ddea56d2f9d02f1c38ae3c5dc400e1fc63920d0b9bf4d614b212330b3c3b188b1f71a4f428abc5b79bee6bb9bc9f98db7673bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
